### ISSUE TITLE
基础知识回顾

### ISSUE THREAD

**Issue by Weiting-Zhang** [Weiting-Zhang/Weiting-Zhang.github.io#1]
#### #水平居中
行内元素设置 text-align：center
定宽元素 设置左右margin为auto
以下垂直居中也包括的部分
#### #垂直居中
如果是行内元素，设置lineheight等于高度；

一些具体方法：
``` css
// 兼容性好
.align-center{
 /**
    * 负边距+定位：水平垂直居中（Negative Margin）
    * 使用绝对定位将content的定点定位到body的中心，然后使用负margin（content宽高的一半），
    * 将content的中心拉回到body的中心，已到达水平垂直居中的效果。
    */       
    position:absolute;
    left:50%;
    top:50%;
    width:400px;
    height:400px;
    margin-top:-200px;
    margin-left:-200px;
    border:1px dashed #333;
}
//  不用margin拉回来的方法
.child {
    position  : absolute;
    top       : 50%;
    left      : 50%;
    transform : translate(-50%,-50%);
｝

// 若父容器下只有一个元素，且父元素设置了高度，则只需要使用相对定位即可
.parentElement{ 
     height:xxx; 
} 
.childElement { 
    position: relative; 
    top: 50%; transform:
     translateY(-50%);
 }

// 对父元素
.parent ｛
    display         : flex;
    justify-content : center;
    align-items     : center;
｝

// css3 box
/* W3C */
.container {
    display:box;
    box-pack:center;
    box-align:center
}
```
#### #三栏布局中间自适应
自身浮动法。左栏左浮动，右栏右浮动
绝对定位法。左右两栏采用绝对定位，分别固定于页面的左右两侧，中间的主体栏用左右margin值撑开距离。
Flex。
#### #产生BFC的方式
float的值不为none。
overflow的值不为visible。
display的值为table-cell, table-caption, inline-block中的任何一个。
position的值不为relative和static。
#### #Vue 和 React 相同之处
- 都使用 Virtual DOM
- 都提供了响应式（Reactive）和组件化（Composable）的视图组件。
- 将注意力集中保持在核心库，而将其他功能如路由和全局状态管理交给相关的库。
#### #Vue 的优势
- Vue 更加轻量，性能有少量优势。
- Vue 本身相对于 React 更像一个框架一点，Vue 的理念就像是  React + Mobx。React 更加纯粹，本身只负责 view 层。
#### #怎么理解 Virtual DOM
Virtual DOM 本质上就是在 JS 和 DOM 之间做了一个缓存，DOM 操作这么慢，那就让  JS 只操作这个缓存，最后的时候再把变更写入 DOM。
组件化不一定需要 Virtual DOM，但是如果没有 Virtual DOM，每次更新组件都要把 DOM 删了重建。但是假如有一个能保留 DOM 层次关系和它的基本属性的 JS 对象,，组件的 render 函数都去生成这样一个  Virtual DOM，（而且 Virtual DOM 是 batch update 的），然后和上一次生成的 VIrtual DOM 去 diff ，得到一个 Patch，最后把这个 Patch 一次性打到浏览器的 DOM 上去。JS  对象的操作是很快的，无论重新生成也好还是 diff 也好，而且因为中间有一个 diff 的过程，在 Patch 的时候就可以针对 DOM 操作进行优化，效率更高。（即使没有 diff 也可以处理一些类似于把批量操作合并这样的优化，就像用document fragment 做完所有操作再把它添加到实际 DOM 里一样，但是有 diff 算法效率会更高。）
#### #怎么实现 Virtual DOM
1. 用 JS 对象模拟 DOM 树结构。然后用这个树构建一个真正的 DOM 树，插到文档当中。
2. 当状态变更的时候，重新构造一棵新的对象树。然后用新的树和旧的树进行比较，记录两棵树的差异。
3. 把差异应用到真正的 DOM 树上，完成视图的更新。
#### #那怎么实现 diff 算法
考虑到前端很少跨越层级地去移动 DOM 元素，Virtual DOM 只会对同一个层级的元素进行对比。做法是
1. 深度优先遍历，使每个节点都有唯一的标记。
2. 并记录差异类型，也把它们对应到下标中，差异类型有以下几种
- 替换掉原来节点
- 移动/添加/删除子节点（移动需要列表对比算法）
- 修改了节点的属性
- 对于文本节点内容的改变

3. 列表对比算法
3.1 遍历新列表的每一项，如果该项的 vm 之前就存在，则打一个 _resued 的标，如果不存在，则创建一个新的。
3.2 遍历旧列表的每一项，如果 _resued 的标没有被打上，则说明新列表里已经没有它了，就地销毁。
3.3 重新整理新的 vm 在视图里的顺序，同时还原之前打上的 _reused 标。
（移动可以看成删除和插入操作的结合，抽象出来是字符串的最小编辑距离问题，最常见的解决算法是通过动态规划求解。需要注意的是，由于 TagName 是可重复的，所以需要给子节点加上唯一标识 key，列表对比的时候，用这个 key 进行对比。）
#### #Batch Update 原理
利用了 JavaScript Event loop。当 model 被修改时，对应的 watcher 被推入到一个 update quene，于此同时在异步队列中添加一个 task 用来 flush 当前的 update quene，等当前的 task 的执行结束后，这个 flush task 再执行。 
#### #动态数据绑定(MVVM 思想)
简洁版：把 Model 和 View 建立起关系，然后提供给数据一种观察能力，并在数据变化后更新视图。
清晰版：
1. 通过 Observer 对 data 进行监听，并且提供某个数据项变化的能力。
2. 把 template 解析成一段 document fragment，然后解析其中的 directive，得到每一个 directive 所依赖的数据项及其更新方法。
3. 通过 watcher 把这两点结合起来，即把 directive 中的数据依赖订阅在对应数据的 observer 上，这样等数据变化的时候，就会触发 observer，进而触发相关依赖对应的视图更新方法，最后达到模板原本的关联效果。
**具体实现方法**:  在setter 里触发一个通知函数，通知相关的依赖以达到监听的效果。
#### #双向数据绑定
双向数据绑定只是语法糖
本质：
``` 
  v-bind:value="something"
  v-on:input="something = $event.target.value"
```

**Comment by Weiting-Zhang** [comment]
**mtdp**
> 数组去重
- 利用 ES6 的 Set 数据结构: `Array.from(new Set(arr))`
- 利用 ES6 的 Map 数据结构，把数组元素映射成值和出现频率的哈希表: `const seen = new Map(); arr.filter((a) => !seen.has(a) && seen.set(a, 1))`
- 利用 es5 的 `Array.prototype.indexOf` 方法，如果浏览器不支持这个方法，就遍历一遍数组实现这个方法。

**Comment by Weiting-Zhang** [comment]
> cookie

> 是什么

cookie 是为了辨别用户身份而储存在用户本地终端（Client Side）上的数据（通常经过加密）。（来自维基百科）

> 有啥用

因为HTTP协议是无状态协议，服务器不知道用户上一次做了什么，用这种方式在客户端存储用户信息后在发送请求时为每个请求添加 Cookie HTTP 头，将信息发送回服务器，用于验证客户来自于哪个请求。

> 具体长啥样

![2017-09-04 1](https://user-images.githubusercontent.com/20496882/30019656-e7b7a426-9193-11e7-805f-47ed3732aeae.png)

- 名称(name)：唯一，不区分大小写，需经过 URL 编码。
- 值(value)：字符串值，需经过 URL 编码。
- 域(domain)：cookie 的有效域，也是发送请求会包含 cookie 信息的域。这个值可以包含子域。
- 路径(path)：指定域中的路径。
- 失效时间(expires)
- 安全标志(secure): 指定后，cookie 只有在使用 SSL 连接时才会发送到服务器。

**Comment by Weiting-Zhang** [comment]
> 事件流

> 是什么

以程序的角度说，流是具有方向的数据。 JavaScript 的事件流描述的是页面中接收事件的顺序。

> 长啥样

![001108_ry8q_214423](https://user-images.githubusercontent.com/20496882/30024805-0acaa184-91a8-11e7-85e4-803aa378d13c.png)
DOM2 级事件规定的事件流包括三个阶段：
- 事件捕获阶段。首先发生，为截获事件提供了机会。捕获阶段不涉及事件目标。
- 处于目标阶段
- 事件冒泡阶段。对事件做出响应。事件处理被看成冒泡阶段的一部分。

**Comment by Weiting-Zhang** [comment]
> # ES6

> let 

> 为什么要有？

ES5 只有全局作用域和函数作用域。let const 增加块级作用域，并避免不正常的声明提升，使程序运行更加合理。比如用来计数的循环变量不会泄露为全局变量等。

> 有哪些特性？

- 块级作用域中声明的内层变量不会影响外层作用域中的变量。
- 不允许在同一作用域内重复声明(var 可以)。
- 不存在声明提升，但存在暂时性死区。（只要块级作用域中存在 `let` 命令，所声明的变量就绑定这个区域，不受外部的影响）

> const

> 干啥用的？

const 用来声明一个只读的常量。

> 有什么特性？

- 一旦声明，常量的值就不能改变。
- 声明时就需要被赋值。
- 块级作用域。
- 不允许重复声明。
- 不存在声明提升，但存在暂时性死区。
- 保证的是声明变量指向的地址不可变。

**Comment by Weiting-Zhang** [comment]
> # ES6

> 解构赋值

> 用途？

- 交换变量 [x, y] = [y, x]
- 从函数中返回多个值
- 参数定义
- 提取 JSON 数据
- 为函数参数提供默认值
- 加载模块的指定方法

**Comment by Weiting-Zhang** [comment]
> ES6

> Set

> 是什么？

构造函数。用来生成 Set 数据结构，没有重复的值。
``` js
const s = new Set();
[1, 2, 2].forEach(x => s.add(x));
```

> 怎么用？

- 与（类）数组相互转化
接受一个数组(或者具有 iterable 接口的其他数据结构) 作为参数来初始化。
利用解构扩展运算符 `[...set]`  或者数组的新方法 `Array.from(set)` 把 Set 转化为数组。

**Comment by Weiting-Zhang** [comment]
> # ES6

>Map

> 干啥用的?

提供“值-值”的对应。一种更完善的 Hash 结构的实现。

> 怎么用？

**Comment by Weiting-Zhang** [comment]
> # ES6

> Promise

> 是什么？

一种异步的解决方案，是一个对象，(一个容器)，里面保存着未来才会结束的事件。

> 怎么用？

接受一个函数为参数，该函数的两个参数分别为 `resolve` 和 `reject` ， `resolve(value)`  把 `Promise` 对象的状态从 `pending` 变为 `resolved` , 并把异步调用的结果作为参数传递出去。`reject(error)` 把 `Promise` 对象的状态从 `pending` 变为 `rejected` 并把异步操作报出的错误传递出去。
``` js
var promise = new Promise((resolve, reject) => {
    if(/* 异步操作成功 */) {
    resolve(value);
    } else {
        reject(error);
    }
})

**Comment by Weiting-Zhang** [comment]
> JavaScript 数据类型有几种？

七种。前六种是 `undifined`, `null`, `Boolean`, `String`, `Number`, `Object`。第七种是新增的 `Symbol`。

**Comment by Weiting-Zhang** [comment]
> this 的值有几种？

**Comment by Weiting-Zhang** [comment]
> 函数的调用方法有几种？

**Comment by Weiting-Zhang** [comment]
> 箭头函数？

- 一个箭头函数表达式的语法比一个函数表达式更短，并且不绑定自己的 `this`，`arguments`，`super`或 `new.target`。

**Comment by Weiting-Zhang** [comment]
> # grid 布局？

**Comment by Weiting-Zhang** [comment]
> flex 布局？

**Comment by Weiting-Zhang** [comment]
> ## 水平居中?
行内元素设置 text-align：center
定宽元素 设置左右margin为auto
以下垂直居中也包括的部分
> ## 垂直居中?
如果是行内元素，设置lineheight等于高度；

一些具体方法：
``` css
// 兼容性好
.align-center{
 /**
    * 负边距+定位：水平垂直居中（Negative Margin）
    * 使用绝对定位将content的定点定位到body的中心，然后使用负margin（content宽高的一半），
    * 将content的中心拉回到body的中心，已到达水平垂直居中的效果。
    */       
    position:absolute;
    left:50%;
    top:50%;
    width:400px;
    height:400px;
    margin-top:-200px;
    margin-left:-200px;
    border:1px dashed #333;
}
//  不用margin拉回来的方法
.child {
    position  : absolute;
    top       : 50%;
    left      : 50%;
    transform : translate(-50%,-50%);
｝

// 若父容器下只有一个元素，且父元素设置了高度，则只需要使用相对定位即可
.parentElement{ 
     height:xxx; 
} 
.childElement { 
    position: relative; 
    top: 50%; transform:
     translateY(-50%);
 }

// 对父元素
.parent ｛
    display         : flex;
    justify-content : center;
    align-items     : center;
｝

// css3 box
/* W3C */
.container {
    display:box;
    box-pack:center;
    box-align:center
}
```
#### #三栏布局中间自适应
自身浮动法。左栏左浮动，右栏右浮动
绝对定位法。左右两栏采用绝对定位，分别固定于页面的左右两侧，中间的主体栏用左右margin值撑开距离。
Flex。
